# Generated by Django 3.2.9 on 2021-11-14 21:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_course', models.CharField(max_length=100)),
                ('tee_time', models.DateTimeField()),
                ('description', models.CharField(help_text='Write a description in 200 words or less', max_length=200)),
                ('game_type', models.CharField(choices=[('s', '2-Man Scramble'), ('f', 'Freeplay')], default='f', max_length=1)),
            ],
            options={
                'ordering': ['tee_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=1000)),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('handicap', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(54.0)])),
                ('favorite_course', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('handicap__gte', 0.0), ('handicap__lte', 54.0)), name='profile_handicap_range'),
        ),
    ]
