# Generated by Django 3.2.9 on 2021-11-19 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('handicap', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(54.0)])),
                ('favorite_course', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GolfGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_course', models.CharField(max_length=100)),
                ('tee_date', models.DateField()),
                ('tee_time', models.TimeField()),
                ('description', models.TextField(max_length=200)),
                ('game_type', models.CharField(choices=[('2-Man Scramble', '2-Man Scramble'), ('Freeplay', 'Freeplay')], default='f', max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('handicap__gte', 0.0), ('handicap__lte', 54.0)), name='profile_handicap_range'),
        ),
    ]
