# Generated by Django 3.2.9 on 2021-11-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_course', models.CharField(max_length=100)),
                ('tee_time', models.DateTimeField()),
                ('description', models.CharField(help_text='Write a description in 200 words or less', max_length=200)),
            ],
            options={
                'ordering': ['tee_time'],
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
