# Generated by Django 3.2.9 on 2021-11-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfgroup',
            options={},
        ),
    ]
