# Generated by Django 3.2.9 on 2021-11-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211114_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfgroup',
            name='game_type',
            field=models.CharField(choices=[('s', '2-Man Scramble'), ('f', 'Freeplay')], default='f', max_length=1),
        ),
    ]
