# Generated by Django 3.2.9 on 2021-11-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_golfgroup_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfgroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='main_app.profile'),
        ),
    ]
