# Generated by Django 3.2.9 on 2021-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_golfgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile/profile-image-default.jpeg', null=True, upload_to='profile'),
        ),
    ]
